# logistic regression model for heart_statlog_cleveland_hungary dataset

In [146]:
## the taken dataset are already 85% cleaned so we not required to preprocess more.

In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

In [111]:
# used to import dataset
df = pd.read_csv("heart_statlog_cleveland_hungary_final.csv")
df

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
...   ...  ...              ...           ...          ...   
1185   45    1                1           110          264   
1186   68    1                4           144          193   
1187   57    1                4           130          131   
1188   57    0                2           130          236   
1189   38    1                3           138          175   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0             172                0   
1                       0            0             156                0   
2                       0            1              98                0   
3                       0            0             108                1   
4                       0            0             122                0   
...                   ...          ...             ...              ...   
1185                    0            0             132                0   
1186                    1            0             141                0   
1187                    0            0             115                1   
1188                    0            2             174                0   
1189                    0            0             173                0   

      oldpeak  ST slope  target  
0         0.0         1       0  
1         1.0         2       1  
2         0.0         1       0  
3         1.5         2       1  
4         0.0         1       0  
...       ...       ...     ...  
1185      1.2         2       1  
1186      3.4         2       1  
1187      1.2         2       1  
1188      0.0         2       1  
1189      0.0         1       0  

[1190 rows x 12 columns]

In [90]:
# it give the shape of the data (number of rows, number of columns)
df.shape

(1190, 12)

In [91]:
# it give the basic statisticle measures of the columns
df.describe()

age          sex  chest_pain_type  resting_bp_s  cholesterol  \
count  1190.000000  1190.000000      1190.000000   1190.000000  1190.000000   
mean     53.720168     0.763866         3.232773    132.153782   210.363866   
std       9.358203     0.424884         0.935480     18.368823   101.420489   
min      28.000000     0.000000         1.000000      0.000000     0.000000   
25%      47.000000     1.000000         3.000000    120.000000   188.000000   
50%      54.000000     1.000000         4.000000    130.000000   229.000000   
75%      60.000000     1.000000         4.000000    140.000000   269.750000   
max      77.000000     1.000000         4.000000    200.000000   603.000000   

       fasting_blood_sugar  resting_ecg  max_heart_rate  exercise_angina  \
count          1190.000000  1190.000000     1190.000000      1190.000000   
mean              0.213445     0.698319      139.732773         0.387395   
std               0.409912     0.870359       25.517636         0.487360   
min               0.000000     0.000000       60.000000         0.000000   
25%               0.000000     0.000000      121.000000         0.000000   
50%               0.000000     0.000000      140.500000         0.000000   
75%               0.000000     2.000000      160.000000         1.000000   
max               1.000000     2.000000      202.000000         1.000000   

           oldpeak     st_slope       target  
count  1190.000000  1190.000000  1190.000000  
mean      0.922773     1.624370     0.528571  
std       1.086337     0.610459     0.499393  
min      -2.600000     0.000000     0.000000  
25%       0.000000     1.000000     0.000000  
50%       0.600000     2.000000     1.000000  
75%       1.600000     2.000000     1.000000  
max       6.200000     3.000000     1.000000

In [92]:
# it find the columns having the NAN values. if there is any null/NAN value then it will show True
df.isnull()

age    sex  chest_pain_type  resting_bp_s  cholesterol  \
0     False  False            False         False        False   
1     False  False            False         False        False   
2     False  False            False         False        False   
3     False  False            False         False        False   
4     False  False            False         False        False   
...     ...    ...              ...           ...          ...   
1185  False  False            False         False        False   
1186  False  False            False         False        False   
1187  False  False            False         False        False   
1188  False  False            False         False        False   
1189  False  False            False         False        False   

      fasting_blood_sugar  resting_ecg  max_heart_rate  exercise_angina  \
0                   False        False           False            False   
1                   False        False           False            False   
2                   False        False           False            False   
3                   False        False           False            False   
4                   False        False           False            False   
...                   ...          ...             ...              ...   
1185                False        False           False            False   
1186                False        False           False            False   
1187                False        False           False            False   
1188                False        False           False            False   
1189                False        False           False            False   

      oldpeak  st_slope  target  
0       False     False   False  
1       False     False   False  
2       False     False   False  
3       False     False   False  
4       False     False   False  
...       ...       ...     ...  
1185    False     False   False  
1186    False     False   False  
1187    False     False   False  
1188    False     False   False  
1189    False     False   False  

[1190 rows x 12 columns]

In [93]:
# it find the number of empty/Null/NAN values in the columns
df.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp_s           0
cholesterol            0
fasting_blood_sugar    0
resting_ecg            0
max_heart_rate         0
exercise_angina        0
oldpeak                0
st_slope               0
target                 0
dtype: int64

In [72]:
df.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target  
0            0             172                0      0.0         1       0  
1            0             156                0      1.0         2       1  
2            1              98                0      0.0         1       0  
3            0             108                1      1.5         2       1  
4            0             122                0      0.0         1       0

In [95]:
from sklearn.model_selection import train_test_split  # It is used to divide/split the data in train and test  
from sklearn.preprocessing import StandardScaler  # It is used to bring the datapoints in the same scale (data scaling)
from sklearn.linear_model import LogisticRegression   # It is used to build the logistic regression model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  # it cosists of model evaluation parameters

In [96]:
# the space between the columns name is change to the '_' 
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [97]:
# X :- it is a features of we are using for training the model
# y :- it is a target column

X = df.drop("target", axis=1)
y = df["target"]


In [98]:
# here we are spliting the data in 8:2 ratio, 80% used for training and 20% used for testing

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)


In [77]:
# it is used for bringing the data in the same scale

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [99]:
# model building using sklearn logistic regression and fitting the data to the model.

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [100]:
# it give the prediction from the test data
y_pred = model.predict(X_test_scaled)
print(y_pred)

[1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0
 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1 1
 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1
 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1
 0 0 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0
 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1]


In [102]:
# it give the accuracy of the model (here 84% accurate the model is answering)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8403361344537815


In [104]:
# these are the weights of the features

model.coef_

array([[ 0.21727569,  0.62130291,  0.69304451,  0.13114537, -0.25181841,
         0.38303257,  0.00717206, -0.22052714,  0.5086149 ,  0.40022507,
         0.78121404]])

In [105]:
# it is the intercept of the equation

model.intercept_

array([0.22567718])

# logistic regression model for Diabetes dataset

In [106]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

In [109]:
# used to import dataset
df1 = pd.read_csv("diabetes.csv")
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [115]:
# it give the shape of the data (number of rows, number of columns)
df1.shape

(768, 9)

In [116]:
# it give the basic statisticle measures of the columns
df1.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [117]:
# it find the columns having the NAN values. if there is any null/NAN value then it will show True
df1.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [118]:
# it find the number of empty/Null/NAN values in the columns
df1.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [119]:
from sklearn.model_selection import train_test_split  # It is used to divide/split the data in train and test  
from sklearn.preprocessing import StandardScaler  # It is used to bring the datapoints in the same scale (data scaling)
from sklearn.linear_model import LogisticRegression   # It is used to build the logistic regression model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  # it cosists of model evaluation parameters

In [123]:
# X :- it is a features of we are using for training the model
# y :- it is a target column

X_1 = df1.drop("Outcome", axis=1)
y_1 = df1["Outcome"]

In [125]:
# here we are spliting the data in 8:2 ratio, 80% used for training and 20% used for testing

X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split( X_1, y_1, test_size=0.2, random_state=42, stratify=y)


In [127]:
# it is used for bringing the data in the same scale

scaler_1 = StandardScaler()
X_train_scaled_1 = scaler_1.fit_transform(X_train_1)
X_test_scaled_1 = scaler_1.transform(X_test_1)

In [137]:
# model building using sklearn logistic regression and fitting the data to the model.

model_1 = LogisticRegression(max_iter=1000)
model_1.fit(X_train_scaled_1, y_train_1)

LogisticRegression(max_iter=1000, solver='liblinear')

In [138]:
# it give the prediction from the test data
y_pred_1 = model_1.predict(X_test_scaled_1)
print(y_pred_1)

[1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0]


In [139]:
# it give the accuracy of the model (here 84% accurate the model is answering)
print("Accuracy:", accuracy_score(y_test_1, y_pred_1))

Accuracy: 0.7142857142857143


In [140]:
# these are the weights of the features

model.coef_

array([[ 0.37317821,  1.14415127, -0.19763683,  0.06653497, -0.12730823,
         0.71389341,  0.25552675,  0.18417899]])

In [141]:
# it is the intercept of the equation

model.intercept_

array([-0.87496049])